name: build libclang.wasm

on:
  workflow_dispatch:
    inputs:
      llvmCommit:
        description: 'llvm-project commit SHA'
        required: true
        default: '3b5b5c1ec4a3095ab096dd780e84d7ab81f3d7ff'

env:
  EM_VERSION: 3.1.61
  EM_CACHE_FOLDER: 'emsdk-cache'

jobs:
  _:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      # setup the ninja build tool
      - uses: seanmiddleditch/gha-setup-ninja@v5

      - name: cache emscripten
        id: cache-system-libraries
        uses: actions/cache@v4
        with:
          path: ${{env.EM_CACHE_FOLDER}}
          key: ${{env.EM_VERSION}}-${{ runner.os }}

      - name: setup emscripten
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: ${{env.EM_VERSION}}
          actions-cache-folder: ${{env.EM_CACHE_FOLDER}}
      
      # build llvm from source
      - name: fetch and build llvm-project
        run: ./build-llvm.sh ${{ inputs.llvmCommit }}

      - name: build libclang.wasm
        run: ./build-libclang.sh
      
      # pack the outputs for release
      - name: tar assets
        working-directory: ./out
        run: |
          mkdir -p ./release
          tar cvzf ./release/llvm-build.tar.gz ./install/
          tar cvzf ./release/libclang.tar.gz ./bin/
      
      # create a draft release
      - name: draft release
        uses: softprops/action-gh-release@v2
        with:
          name: "lllvm-project ${{ inputs.llvmCommit }} + emcc ${{ env.EM_VERSION }}"
          body: "libclang.wasm built with emcc ${{ env.EM_VERSION }} using the ${{ inputs.llvmCommit }} commit of the llvm-project"
          draft: true
          files: |
            ./out/release/llvm-build.tar.gz
            ./out/release/libclang.tar.gz